### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by bakape** [bakape/pdb#1]
### TODO

- [ ] Switch to SQL using https://github.com/andygrove/sqlparser-rs - has the advantage of being prolific and we can use PostgreSQL SQL extensions like return and arrays.

### General ideas
- [ ] To ease development implement a psql-like shell early on
  - [ ] Can be root-only with no authentication for now
  - [ ] Must have database switching with `\d` like Postgres
- [ ] A transaction is always one statement
  - [ ] This allows for ahead of time locking on all tables needed for the transaction. The query builder should bubble the table and lock types needed.
  - [ ] Also enables hot reload support via forking into a child and a global readiness mutex
- [ ] Support generic containers - arrays (`[]` or `array<>`), `map<>` and `set<>` to allow denormalization for avoiding joins. 
  - [ ] Store the entire collection in one line in the page
  - [ ] Implement various methods and operators 
- [ ] Support filter, map, reduce, group (a specialized map + reduce) for aggregation and filter building
- [ ] Support equality, and, or, between and ordering comparisons (gt, lt, ...)  
- [ ] Support logical operators - if, and, or
- [ ] Postgres-like `returning` suffix to support returning data after non-select statements   
- [ ] Postgres-like `on_conflict` suffix for insert, update and delete
- [ ] Aggregation reduction functions 
- [ ] Allow complex statement chaining and nesting via a query builder
- [ ] Parallel table and index scans via rayon
- [ ] Binary-encodable request structs for network transport 
- [ ] Cache query plans by serialized request structs
  - [ ] Clear plan cache cache and lazily recompute all affected plans on schema change 
- [ ] Paging using 4 KB `malloc`
  - [ ] Track last access time of table and index pages
    - [ ] This requires to protect the pages with RW locks and automatically read and decompress a page, if it is requested.
    - [ ] Update LRU both on free lock acquisition and release. 
      - [ ] Do not update LRU, if lock already taken (either on read lock acquisition or realise) . No need to fetch the current time or update the LRU in the registry for this. Will need to implement our own mutex with LRU for this.  
 - [ ] Reserve up to 30% (configurable) of all page memory as "ZSWAP". When there is not enough memory to allocate a page (accounting for 64 MB (configurable) as reserved), compress the LRU page and store it inside ZSWAP, until needed.
   - [ ] Consider not using pages for compressed storage and just preallocating 30% of system memory as ZSWA instead.
   - [ ] If ZSWAP is full, swap the LRU entries inside the ZSWAP to disk, until there is enough to allocate a page.
   - [ ] Allocate 1 MB hugepages for storage.
   - [ ] Always keep 1 extra hugepages unused (unless at max capacity), so there is reserved space to compress pages to.
 - [ ] Ensure new page allocation is don't block much and the allocator performs reclamation async, if no pages are free. 
    - [ ] Perform memory compaction and freeing, when close to the limit. This is because the limit is eventual and not hard.
 - [ ] Provide both a classic and a bump allocator backed by the allocated pages. 
   - [ ] The bump allocator should be used for temporary data structures, like query calculations within a frame. 
 - [ ] If somehow no pages can be swapped neither do ZSWAP or disk, fail the allocation and abort the query.  
 - [ ] Keep recently allocated pages in a `Vec`-backed stack to keep hot pages hot and reduce need to call malloc. 
   - [ ] Limit max capacity of the stack.
   - [ ] On new page acquisition read the current monotonic timestamp. If there has not been a stack shrinkage in a while (configurable), return from stack bottom pages older than some threshold (configurable).   
 - [ ] Use this allocator for all table (both created and temporary aggregate tables) and indices
   - [ ] Create thread-local suballocators for parallel aggregation
   - [ ] Implement in-house collections with page-optimized merging strategies making use of cheap memory copying. 
 - [ ] Zero pages for dynamic size columns on acquisition. This allows skipping inserts of new cells, if they match the zero value or are null.  
- [ ] Composite types
- [ ] No foreign keys. If you need cross-table consistency - store it in one table. 
- [ ] Can be used both as an embedded and external DB service.
- [ ] Table consistency can be ensured by indices
- [ ] API for explicit full table locking against writes
  - [ ] Needs to wait for any running writes to finish as well 
- [ ] Don't sync indices to disk. Just rebuild them from disk on first use
- [ ] Use a separate bounded size, lazily allocating thread pool for processing requests
  - [ ] Block, if max threads already in use
- [ ] Ability to specify a timeout for any query request
- [ ] Mechanism to return number of modified rows from a write statement
- [ ] As there can only be one concurrent write transaction on a table, the path set to be committed can be kept on the table instance itself. 
- [ ] Composite types
- [ ] Enums
- [ ] Allow signed and unsigned integers in the [8;128] bit range and both f32 and f64.
  - [ ] Support standard SQL integers as well
- [ ] If queries in the same read-only frame require the same aggregates, precompute them before the query
  - [ ] Keep aggregates stored indefinitely, until a query that might mutate them is run
- [ ] Deduplicate non-collection heap fields possibly larger than 8 bytes using per-column-per-table compression dictionaries to reduce used memory. This has the additional effect of speeding up equality comparison. 
- [ ] Share prepared statements for the entire database.
  - [ ] Map the prepared statement IDs requested by the client to internal ones.
  - [ ] Allow to specify no prepared statement ID and thus receive an ID generated from the internal ID.
  - [ ] On session close delete all orphaned prepared statements
- [ ] Batch inserts in the same frame, batching index alterations and such
- [ ] Use arenas to allocate temporary buffers and drop/reuse them at the end of the frame. Use those for all collections. 
- [ ] Add generic `low_cardinality<>` type that marks its values as having low cardinality and thus viable for direct match dictionary compression. 
- [ ] Make tables and composite types as compatible as possible.
  - [ ] Automatically create composite types for tables
  - [ ] Make both support checks and features that are not storage-dependant
  - [ ] Allow creating tables from composite types
  - [ ] Check name conflict with associate on creation on renaming. 
- [ ] Declarative partitioning with automatic partition creation.
  - [ ] Client must specify partition division scheme.
  - [ ] Client has no access to  the individual partitions. 
  - [ ] Each partition has its own allocation pool for pages. 
  - [ ] Each partition has its own indexes
  - [ ] Conduct partition pruning and run in parallel on all partitions, if the query can not cause the affected rows to move to a different partition. 
  - [ ] All partitions share a schema. 
  - [ ] Always partition tables, even if, not asked. Default partitioning scheme is by `row_id % 1_000_000`.  
- [ ] Trigger and method system using C++ header files with templates or Rust functions with macros for running queries.
  - [ ] Client is free to write it as C with templates for dynamic values like rows. 
  - [ ] Make this the execution context of the trigger.
  - [ ] Compile trigger on `create trigger`by producing a separate dynamic library.
    - [ ] Load lib after compilation. 
    - [ ] Unload lib on trigger removal.
    - [ ] Map internal types to C++ wrapper classes, that are instantiated during trigger call. 
      - [ ] Support DB generics, like collections. 
    - [ ] Recompile the triggers and methods on schema change.  
    - [ ] Triggers must annotate that they can modify the row at compile time. 
      - [ ] Check this at compile time. 
- [ ] Each generated aggregate should use it's own allocator. That way:
    - [ ] You can simply return all of its pages to the page pool, when deallocating an aggregates.
    - [ ] Can easily share aggregates between threads without causing cache thrashing.
- [ ] Global page allocator
  - [ ] Any thread can request a new page
  - [ ] Don't immediately deallocate pages and instead keep the average requested pages during the last N frames in the pool.
- [ ] Batch queries by page, so page scans can be parallelized.
  - [ ] Indexes should only store row ID
  - [ ] Pages of rows should be looked up in a dedicated lookup map before performing any scans.    
- [ ] Optionally specify table ordering to increase query locality
  - [ ] Ordering is not maintained during inserts and updates but maintained by a background task
  - [ ] Allow reordering a table concurrently.
- [ ] Cache SQL ASTs and prepared statements by SQL string.
  - [ ] Evict based on LRU periodically
  - [ ] Figure out how to fit this into the SQL prepared statement API.
- [ ] Perform sequential scan filters in parallel using atomic bitwise operations
- [ ] Make the user explicitly specify what index kind to use for all index DDL statements.
  - [ ] Document that hasmap indexes are faster and should be used, if you don't intend to order by the indexed columns. 
- [ ] Port `brownhash` maps and sets to use the locking ZSWAPing allocator with page locking on use. 
- [ ] Ability to mark columns as `const` (via table creation or alter table). `const` columns can not be updated. This allows for easy restriction triggers and locking optimisations.   
- [ ] Join indices. See other DBs for inspiration. 

### Page structure

- [ ] Store each column in its own page pool.
- [ ] To prevent row_id wraparound periodically rebuild the column with row_id remapping  
- [ ] Static size columns
  - [ ] Determine page as `row_id % page_capacity`
  - [ ] Pages are sparse arrays
  - [ ] Store nullity bitmask in page header
  - [ ] Enums should be stored as smallest aligned fitting capacity integers 

```
<presence bitmask (because page is a sparse array)>
<nullity bitmask (omitted, if column can not be null)>
<column values in row ID order>
```

- [ ] `low_cardinality<type>`
  - [ ] Store as a bidirectional map of `value pointer -> row ID set` and `row ID -> value pointer`
  - [ ] To prevent duplicate value allocations, store pointers to actual values in an append-only vector with the same lifetime as the column struct. 

- [ ] All other column types
  - [ ] Advise against usage in docs. Suggest `enums` or `low_cardinality<type>`
  - [ ] Maintain freelists both on the page and column level
  - [ ] Maintain registry of what column is allocated in what page
  - [ ] Periodic rebuilds to defragment and reorder
  - [ ] Store registry of what row is allocated in what page-local virtual memory address 
  - [ ] Compress values bigger than 64 bytes (configurable)
    - [ ] Store bitmask of which entries are compressed 
  - [ ] Reject values that are larger than page capacity, even when compressed. Consider that misuse of the DBMS.   

### Fault tolerance
- [ ] Append-only write log file
- [ ] Start with DDL, followed by all the databases compressed table data, column by column 
- [ ] Once LZ4 (or similar) compressed entry per line
  - [ ] Escape newlines in the compressed buffers.
  - [ ] All append operations must be atomic. If the update is too big for one atomic append, encase payload in continuation header and footer.
    - [ ] Discard any unterminated continuations as invalid due to non-atomic write failure.  
- [ ] Concurrent compaction routine
  1. Record length of current log. 
  2. Take a snapshot of all the database's column pages and schema. This can be done via a copy on write indirection layer. 
  3. Dump the snapshotted schema into the file.
  4. Dump all the column data into the file.
  6. Append any concurrent changes from the original file.   
  7. Swap the files
  8. Delete old log file
- [ ] Single append size must not exceed POSIX PIPE_BUF  (4KB on EXT3+ under Linux)
  - [ ] If size is exceeded even for a compressed update, split messages and write them sequentially in to the file. 
  - [ ] An unclosed split message is considered not committed and thus garbage. 
- [ ] Allow schema migrations to be performed asynchronously to reduce blocking. 

### Table locking strategy
- [ ] Column-level locks and table-level locks
  - [ ] Selects and updates lock only affected rows
  - [ ] Inserts and deletes lock the entire table
- [ ] Only serializable transactions 
- [ ] A lock on a table also acquires a lock on all tables with foreign keys referencing this table
- [ ] A schema change acquires a lock on the entire DB
  - [ ] Defer request SQL validation to after a schema change, if there is any, to not have to revalidate it again. 
  - [ ] Alway schedule a schema change to the back of the queue.    
- [ ] Perform all allocations for a transaction using it's own arena.
- [ ] Enable scheduling some read and write transactions on the same table by emulating the read transactions executing before the write transactions. This can be done by building and mutation override overlay over any such tables and having both read and write queries use the immutable table data beneath. 

### Implementation
API-first approach: start work with the statement builder and query planner.

### Micro optimizations 
 - [ ] Use brownhash to allow mapping value vectors into hash-value tuples in parallel and building hashmaps from that with a pregenerated hasher. 
- [ ] Memoize enum-only hashes on DDL calls with a constant hasher.
  - [ ] Hash random seed should be generated on DB load and apply to all hash maps and sets contained. This is a compromise that enables hash memorization, but still is resilient enough to DoS attacks. 

### Ops support
- [ ] Support zero downtime software and hardware migration by pausing replication log compaction, copying it the log up to a recorded point and then atomically transferring ther new entries of the replication log and prepared statement registry.  
  - [ ] Log format has to remain backwards-compatible 
  - [ ] Switching from one instance to the next can be done via a small dedicated reverse proxy.
    - [ ] Signal the reverse proxy to switch before server shutdown, together with client IDs and request that should be retried.
- [ ] Support fallback replicas with synchronous replication log propagation. 

### Concurrent bitmap filter combination

```
start filtrer A 
start filter B
let C be the first to finish of A and B
let D be the other filter
if D has not finished yet
  sleep 1 for second
  if D has finished
    merge D into C
  else
    kill D
    if D has a partial bitmap
      merge partial result of D into C
    filter range unfinished by D that intersects C 
else
  merge D into C
```

### Replication

- [ ] Allow N read-only replicas per database on the master
- [ ] If present, the read-only requests are reverse-proxied to the replicas
  - [ ] The master maintains consistency, by splicing in update batches between request batches
- [ ] Allow the master to promote a replica to the new master with zero downtime.
